platform:
  - x64

environment:
  CYG_ROOT: "C:\\cygwin64"
  CYG_CACHE: C:/cygwin64/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  CYG_ARCH: "x86_64"
  CYGWIN: "winsymlinks:native"
  CUSTOM_OPAM: "1"
  OPAM_COMP: "4.07.0+mingw64c"
  OPAM_LINT: "false"
  OPAMYES: 1
  OPAMCOLORS: 1
  OPAMVERBOSE: 1
  BINDIR: 'C:\projects\vpnkit'

install:
  - cmd: echo Windows build is disabled until we can remove cygwin.

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/scripts/appveyor.sh'"
