platform:
  - x86

environment:
  global:
    FORK_USER: ocaml
    FORK_BRANCH: master
    CYG_ROOT: C:\cygwin64
    PINS: "hvsock.3.0.0:https://github.com/djs55/ocaml-hvsock.git#release.3.0.0 protocol-9p.2.0.2:https://github.com/djs55/ocaml-9p.git#cstruct.length protocol-9p-unix.2.0.2:https://github.com/djs55/ocaml-9p.git#cstruct.length vpnkit:."
    PACKAGE: "vpnkit"
    OPAM_SWITCH: 4.08.0+mingw64c

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l -x %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
  - call %CYG_ROOT%\bin\bash.exe -l -x %APPVEYOR_BUILD_FOLDER%\scripts\appveyor.sh

artifacts:
  - path: "./_build/default/vpnkit.exe"
  - path: "./_build/default/licenses.json"
  - path: "./_build/default/COMMIT"