platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  EXTRA_REMOTES: "repo"
  PINS: "proto-vmnet:v1/proto-vmnet ofs:v1/ofs hostnet:v1/hostnet osx-daemon:v1/osx-daemon osx-hyperkit:v1/osx-hyperkit slirp:v1/cmd/com.docker.slirp.exe"
  PACKAGE: "com-docker-slirp-exe"
  TESTS: "false"

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils -P curl -P make -P unzip -P git -P m4 -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"
