version: 2
jobs:
  build:
    macos:
      xcode: "12.0"
    environment:
      OPAMYES: "1"
      OPAMJOBS: "2"
      MACOSX_DEPLOYMENT_TARGET: "10.10"
      CUSTOM_OPAM: "1"
      OPAM_REPO: repo/darwin
      OPAM_COMP: "4.07.0"
      OPAMVERBOSE: 1
      TERM: vt100
    steps:
      - checkout
      - run: brew update
      - run: brew install wget
      - run: brew install pkg-config
      - run: brew install dylibbundler
      - run: brew install opam
      - run: make -f Makefile.darwin depends
      - run: make -f Makefile.darwin
      - run: make -f Makefile.darwin artefacts
      - run: make -f Makefile.darwin test
      - store_artifacts:
          path: vpnkit.tgz
      - store_artifacts:
          path: COMMIT
      - store_artifacts:
          path: OSS-LICENSES
workflows:
  version: 2
  build-test-vpnkit:
    jobs:
      - build
