version: 2
jobs:
  build:
    macos:
      xcode: "12.0"
    environment:
      OPAMYES: "1"
      OPAMJOBS: "2"
      MACOSX_DEPLOYMENT_TARGET: "10.10"
      CUSTOM_OPAM: "1"
      OPAM_REPO: repo/darwin
      OPAM_COMP: "4.07.0"
      OPAMVERBOSE: 1
      TERM: vt100
    steps:
      - checkout
      - run: brew uninstall python # remove files in /usr/local/bin
      - run: brew install wget pkg-config dylibbundler
      - run: brew install https://gist.githubusercontent.com/djs55/7a94ee5aeb882ef5399c0485d2affdda/raw/bc04ff96e0082d7ee07642337dbb77c51b93d678/opam.rb
      - run: make
      - run: make artefacts
      - run: make test
      - store_artifacts:
          path: vpnkit.tgz
      - store_artifacts:
          path: COMMIT
      - store_artifacts:
          path: OSS-LICENSES
workflows:
  version: 2
  build-test-vpnkit:
    jobs:
      - build
